
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp_____include_bluez_dbus_cpp_adaptor_GattService1_adaptor_h__adaptor__H__
#define __sdbuscpp_____include_bluez_dbus_cpp_adaptor_GattService1_adaptor_h__adaptor__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace bluez {

class GattService1_adaptor
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.GattService1";

protected:
    GattService1_adaptor(sdbus::IObject& object)
        : object_(object)
    {
        object_.registerProperty("UUID").onInterface(INTERFACE_NAME).withGetter([this](){ return this->UUID(); });
        object_.registerProperty("Primary").onInterface(INTERFACE_NAME).withGetter([this](){ return this->Primary(); });
        object_.registerProperty("Includes").onInterface(INTERFACE_NAME).withGetter([this](){ return this->Includes(); });
    }

    ~GattService1_adaptor() = default;

private:
    virtual std::string UUID() = 0;
    virtual bool Primary() = 0;
    virtual std::vector<sdbus::ObjectPath> Includes() = 0;

private:
    sdbus::IObject& object_;
};

}} // namespaces

#endif
