
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp_____include_bluez_dbus_cpp_proxy_AgentManager1_proxy_h__proxy__H__
#define __sdbuscpp_____include_bluez_dbus_cpp_proxy_AgentManager1_proxy_h__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace bluez {

class AgentManager1_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.AgentManager1";

protected:
    AgentManager1_proxy(sdbus::IProxy& proxy)
        : proxy_(proxy)
    {
    }

    ~AgentManager1_proxy() = default;

public:
    void RegisterAgent(const sdbus::ObjectPath& agent, const std::string& capability)
    {
        proxy_.callMethod("RegisterAgent").onInterface(INTERFACE_NAME).withArguments(agent, capability);
    }

    void UnregisterAgent(const sdbus::ObjectPath& agent)
    {
        proxy_.callMethod("UnregisterAgent").onInterface(INTERFACE_NAME).withArguments(agent);
    }

    void RequestDefaultAgent(const sdbus::ObjectPath& agent)
    {
        proxy_.callMethod("RequestDefaultAgent").onInterface(INTERFACE_NAME).withArguments(agent);
    }

private:
    sdbus::IProxy& proxy_;
};

}} // namespaces

#endif
