
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp_____include_bluez_dbus_cpp_proxy_Device1_proxy_h__proxy__H__
#define __sdbuscpp_____include_bluez_dbus_cpp_proxy_Device1_proxy_h__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace bluez {

class Device1_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.Device1";

protected:
    Device1_proxy(sdbus::IProxy& proxy)
        : proxy_(proxy)
    {
    }

    ~Device1_proxy() = default;

public:
    void Connect()
    {
        proxy_.callMethod("Connect").onInterface(INTERFACE_NAME);
    }

    void Disconnect()
    {
        proxy_.callMethod("Disconnect").onInterface(INTERFACE_NAME);
    }

    void ConnectProfile(const std::string& uuid)
    {
        proxy_.callMethod("ConnectProfile").onInterface(INTERFACE_NAME).withArguments(uuid);
    }

    void DisconnectProfile(const std::string& uuid)
    {
        proxy_.callMethod("DisconnectProfile").onInterface(INTERFACE_NAME).withArguments(uuid);
    }

    void Pair()
    {
        proxy_.callMethod("Pair").onInterface(INTERFACE_NAME);
    }

    void CancelPairing()
    {
        proxy_.callMethod("CancelPairing").onInterface(INTERFACE_NAME);
    }

public:
    std::string Address()
    {
        return proxy_.getProperty("Address").onInterface(INTERFACE_NAME);
    }

    std::string AddressType()
    {
        return proxy_.getProperty("AddressType").onInterface(INTERFACE_NAME);
    }

    std::string Name()
    {
        return proxy_.getProperty("Name").onInterface(INTERFACE_NAME);
    }

    std::string Icon()
    {
        return proxy_.getProperty("Icon").onInterface(INTERFACE_NAME);
    }

    uint32_t Class()
    {
        return proxy_.getProperty("Class").onInterface(INTERFACE_NAME);
    }

    uint16_t Appearance()
    {
        return proxy_.getProperty("Appearance").onInterface(INTERFACE_NAME);
    }

    std::vector<std::string> UUIDs()
    {
        return proxy_.getProperty("UUIDs").onInterface(INTERFACE_NAME);
    }

    bool Paired()
    {
        return proxy_.getProperty("Paired").onInterface(INTERFACE_NAME);
    }

    bool Connected()
    {
        return proxy_.getProperty("Connected").onInterface(INTERFACE_NAME);
    }

    bool Trusted()
    {
        return proxy_.getProperty("Trusted").onInterface(INTERFACE_NAME);
    }

    void Trusted(const bool& value)
    {
        proxy_.setProperty("Trusted").onInterface(INTERFACE_NAME).toValue(value);
    }

    bool Blocked()
    {
        return proxy_.getProperty("Blocked").onInterface(INTERFACE_NAME);
    }

    void Blocked(const bool& value)
    {
        proxy_.setProperty("Blocked").onInterface(INTERFACE_NAME).toValue(value);
    }

    bool WakeAllowed()
    {
        return proxy_.getProperty("WakeAllowed").onInterface(INTERFACE_NAME);
    }

    void WakeAllowed(const bool& value)
    {
        proxy_.setProperty("WakeAllowed").onInterface(INTERFACE_NAME).toValue(value);
    }

    std::string Alias()
    {
        return proxy_.getProperty("Alias").onInterface(INTERFACE_NAME);
    }

    void Alias(const std::string& value)
    {
        proxy_.setProperty("Alias").onInterface(INTERFACE_NAME).toValue(value);
    }

    sdbus::ObjectPath Adapter()
    {
        return proxy_.getProperty("Adapter").onInterface(INTERFACE_NAME);
    }

    bool LegacyPairing()
    {
        return proxy_.getProperty("LegacyPairing").onInterface(INTERFACE_NAME);
    }

    std::string Modalias()
    {
        return proxy_.getProperty("Modalias").onInterface(INTERFACE_NAME);
    }

    int16_t RSSI()
    {
        return proxy_.getProperty("RSSI").onInterface(INTERFACE_NAME);
    }

    int16_t TxPower()
    {
        return proxy_.getProperty("TxPower").onInterface(INTERFACE_NAME);
    }

    std::map<uint16_t, sdbus::Variant> ManufacturerData()
    {
        return proxy_.getProperty("ManufacturerData").onInterface(INTERFACE_NAME);
    }

    std::map<std::string, sdbus::Variant> ServiceData()
    {
        return proxy_.getProperty("ServiceData").onInterface(INTERFACE_NAME);
    }

    bool ServicesResolved()
    {
        return proxy_.getProperty("ServicesResolved").onInterface(INTERFACE_NAME);
    }

    std::vector<bool> AdvertisingFlags()
    {
        return proxy_.getProperty("AdvertisingFlags").onInterface(INTERFACE_NAME);
    }

    std::map<uint8_t, sdbus::Variant> AdvertisingData()
    {
        return proxy_.getProperty("AdvertisingData").onInterface(INTERFACE_NAME);
    }

private:
    sdbus::IProxy& proxy_;
};

}} // namespaces

#endif
