
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp_____include_bluez_dbus_cpp_proxy_SimAccess1_proxy_h__proxy__H__
#define __sdbuscpp_____include_bluez_dbus_cpp_proxy_SimAccess1_proxy_h__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace org {
namespace bluez {

class SimAccess1_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "org.bluez.SimAccess1";

protected:
    SimAccess1_proxy(sdbus::IProxy& proxy)
        : proxy_(proxy)
    {
    }

    ~SimAccess1_proxy() = default;

public:
    void Disconnect()
    {
        proxy_.callMethod("Disconnect").onInterface(INTERFACE_NAME);
    }

public:
    bool Connected()
    {
        return proxy_.getProperty("Connected").onInterface(INTERFACE_NAME);
    }

private:
    sdbus::IProxy& proxy_;
};

}} // namespaces

#endif
